# Generated by Django 3.0.4 on 2020-03-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='visit',
            name='medicine',
            field=models.ManyToManyField(related_name='visit_medicine', to='clinic.Medicine'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedure',
            field=models.ManyToManyField(related_name='visit_procedure', to='clinic.Procedure'),
        ),
    ]
